import json
from typing import List
from fastapi import APIRouter, BackgroundTasks, HTTPException
from sqlmodel import Session, select
from pydantic import BaseModel
from database import engine
from models import Case
from ai.vector_store import ingest_pdf_into_vector_store, ingest_url_into_vector_store
from ai.summarizer import generate_url_summary

router = APIRouter()

class URLSummaryRequest(BaseModel):
    url: str

@router.post("/api/vault/summarize-url")
def summarize_vault_url(req: URLSummaryRequest):
    """
    Takes a URL, fetches its content, and returns a nicely formatted Markdown summary
    generated by the AI. Use this to display detailed info when a user clicks a URL
    in the vault.
    """
    summary = generate_url_summary(req.url)
    return {"summary": summary}


@router.get("/api/cases")
def get_cases():
    with Session(engine) as session:
        cases = session.exec(select(Case)).all()
        
    result = []
    for c in cases:
        # Construct frontend-friendly case
        
        # map backend status to frontend CaseStatus
        status_map = {
            "pending": "active",
            "active": "active",
            "closed": "closed",
            "archived": "archived",
            "success": "success",
            "abandoned": "abandoned"
        }
        frontend_status = status_map.get(c.status, "active")
        
        vault = []
        
        # 1. Parse URLs
        try:
            urls_raw = getattr(c, 'urls_json', '[]') or '[]'
            urls = json.loads(urls_raw)
            
            summaries_raw = getattr(c, 'url_summaries_json', '{}') or '{}'
            url_summaries = json.loads(summaries_raw)
            
            for u in urls:
                vault.append({
                    "id": f"url-{len(vault)}",
                    "type": "url",
                    "name": u,
                    "url": u,
                    "summary": url_summaries.get(u, ""),
                    "addedAt": c.created_at.strftime("%H:%M")
                })
        except Exception as e:
            print(f"[cases] Error parsing URLs for case {c.id}: {e}")


        # 2. Parse PDFs
        try:
            pdfs_raw = getattr(c, 'pdf_paths_json', '[]') or '[]'
            pdfs = json.loads(pdfs_raw)
            for p in pdfs:
                filename = p.split("/")[-1] if "/" in p else p
                vault.append({
                    "id": f"pdf-{len(vault)}",
                    "type": "pdf",
                    "name": filename,
                    "url": f"http://localhost:8000/api/files/{filename}",
                    "addedAt": c.created_at.strftime("%H:%M")
                })
        except Exception as e:
            print(f"[cases] Error parsing PDFs for case {c.id}: {e}")

        # 3. Parse Images
        try:
            imgs_raw = getattr(c, 'image_paths_json', '[]') or '[]'
            images = json.loads(imgs_raw)
            for img in images:
                filename = img.split("/")[-1] if "/" in img else img
                vault.append({
                    "id": f"image-{len(vault)}",
                    "type": "image",
                    "name": filename,
                    "url": f"http://localhost:8000/api/files/{filename}",
                    "addedAt": c.created_at.strftime("%H:%M")
                })
        except Exception as e:
            print(f"[cases] Error parsing Images for case {c.id}: {e}")
            
        name = "New Case"
        if c.context:
            name = c.context[:40] + ("..." if len(c.context) > 40 else "")
        else:
            name = f"Case #{c.id}"

        result.append({
            "id": str(c.id),
            "name": name,
            "caseType": "Legal Research",
            "attorney": "AI Assistant",
            "openedDate": c.created_at.strftime("%b %d, %Y"),
            "status": frontend_status,
            "researchStatus": c.status,
            "messages": [],
            "vault": vault
        })
        
    return result


@router.post("/api/cases/{case_id}/reindex")
def reindex_case(case_id: int, background_tasks: BackgroundTasks):
    """
    Re-ingests all PDFs and URLs for an existing case into the vector store.

    Use this for cases that were created before the vector store was added,
    or if the vector store data was deleted and needs to be rebuilt.

    Example: POST /api/cases/1/reindex
    """
    with Session(engine) as session:
        case = session.get(Case, case_id)
        if not case:
            raise HTTPException(status_code=404, detail=f"Case {case_id} not found")

        pdfs_raw = getattr(case, 'pdf_paths_json', '[]') or '[]'
        pdf_paths = json.loads(pdfs_raw)
        urls_raw = getattr(case, 'urls_json', '[]') or '[]'
        urls = json.loads(urls_raw)

    total_files = len(pdf_paths) + len(urls)

    if total_files == 0:
        return {"message": "No files to index for this case.", "total_files": 0}

    # Ingest each file in the background so the API responds immediately
    for pdf_path in pdf_paths:
        background_tasks.add_task(ingest_pdf_into_vector_store, case_id, pdf_path)

    for url in urls:
        background_tasks.add_task(ingest_url_into_vector_store, case_id, url)

    return {
        "message": f"Reindexing {total_files} file(s) for case {case_id}. This runs in the background.",
        "pdfs": len(pdf_paths),
        "urls": len(urls),
    }


class AddURLRequest(BaseModel):
    url: str

@router.post("/api/cases/{case_id}/add-url")
def add_url_to_case(case_id: int, req: AddURLRequest, background_tasks: BackgroundTasks):
    """
    Adds a new URL to an existing case, triggers background ingestion,
    and re-queues background research so the agent uses the new content.
    """
    with Session(engine) as session:
        case = session.get(Case, case_id)
        if not case:
            raise HTTPException(status_code=404, detail=f"Case {case_id} not found")

        urls_raw = getattr(case, 'urls_json', '[]') or '[]'
        urls = json.loads(urls_raw)
        urls.append(req.url)
        case.urls_json = json.dumps(urls)
        case.status = "pending"
        session.add(case)
        session.commit()

    background_tasks.add_task(ingest_url_into_vector_store, case_id, req.url)

    from ai.background import enqueue_research
    enqueue_research(case_id)

    return {"message": f"URL added and ingestion started for case {case_id}", "url": req.url}


class AddContextRequest(BaseModel):
    context: str

@router.post("/api/cases/{case_id}/add-context")
def add_context_to_case(case_id: int, req: AddContextRequest):
    """
    Appends additional context notes to an existing case and re-queues
    background research so the agent uses the updated context.
    """
    with Session(engine) as session:
        case = session.get(Case, case_id)
        if not case:
            raise HTTPException(status_code=404, detail=f"Case {case_id} not found")

        existing = case.context or ""
        separator = "\n\n" if existing.strip() else ""
        case.context = existing + separator + req.context.strip()
        case.status = "pending"
        session.add(case)
        session.commit()

    from ai.background import enqueue_research
    enqueue_research(case_id)

    return {"message": f"Context updated and research re-queued for case {case_id}"}
